image: ghcr.io/sushrut1101/docker:arch

variables:
  FOX_SYNC: "https://gitlab.com/OrangeFox/sync.git"
  CONFIG: "config.sh"

OrangeFox-CI:
  stage: build
  timeout: 3 hours
  script:
    - source config.sh
    - curl -sL https://raw.githubusercontent.com/AndroidAppsUsedByMyself/OrangeFox-CI/pstar/scripts/checks.sh | bash
    - curl -sL https://raw.githubusercontent.com/AndroidAppsUsedByMyself/OrangeFox-CI/pstar/scripts/sync.sh | bash
    - curl -sL https://raw.githubusercontent.com/AndroidAppsUsedByMyself/OrangeFox-CI/pstar/scripts/build.sh | bash
    - curl -sL https://raw.githubusercontent.com/AndroidAppsUsedByMyself/OrangeFox-CI/pstar/scripts/upload.sh | bash
